MODEL:
  method: PatchCore
  backbone: wide_resnet50_2
  params:
    input_shape:
      - 3 
      - 224
      - 224
    layers_to_extract_from: 
      - layer2
      - layer3
    faiss_on_gpu: True
    faiss_num_workers: 4
    weight_method: identity # identity lof nearest gaussian
    threshold: 0.15
    lof_k: 6
    with_soft_weight: False
    sampler_name: approx_greedy_coreset
    sampling_ratio: 0.1
    anomaly_score_num_nn: 5 # n_nearest_neighbours

DATASET:
  aug_info: 
    - PatchCore