DEFAULT:
  seed: 0
  savedir: ./results/benchmark
DATASET:
  datadir: ../Data
  batch_size: 32
  test_batch_size: 64
  num_workers: 8
  dataset_name: MVTecAD  # [AnomalyDataset,MVTecAD]
  aug_info: null
  anomaly_ratio: 0
  class_name: bottle  