DEFAULT:
  seed: 0
  savedir: ./results/benchmark
DATASET:
  datadir: ../Data/MVtecAD
  batch_size: 32
  test_batch_size: 64
  num_workers: 8
  dataset_name: MVTecAD  # [AnomalyDataset,MVTecAD]
  params:
    class_name: bottle  
  anomaly_ratio: 0.1
  aug_info: null
CRITERION:
  name: MixLoss # [InfoNCE, FeatDist, MixLoss]
  params:
    layers: [0,1,2,3]
    temperature: 0.5
    alpha: 0.1
OPTIMIZER:
  opt_name: AdamW
  lr: 0.01
TRAIN:
  epochs: 30
  grad_accum_steps: 1
  mixed_precision: fp16
  log_interval: 5
  wandb:
    use: true
    project_name: UAADF
MODEL:
  method : STPM
  modelname: resnet18
  pretrained: false
  out_dim: 128
AL:
  n_query: 10
  n_round: 10
  n_subset: null
  init:
    method: random_select