DEFAULT:
  seed: 0
  savedir: ./results/benchmark
DATASET:
  datadir: /Volume/Data
  batch_size: 256
  test_batch_size: 2048
  num_workers: 0
  ID: CIFAR10
  OOD: SVHN
  anomaly_ratio: 0.1
  aug_info: null
CRITERION:
  name: InfoNCE
  params:
    temperature: 0.5
OPTIMIZER:
  opt_name: SGD
  lr: 0.1
TRAIN:
  epochs: 30
  grad_accum_steps: 1
  mixed_precision: fp16
  log_interval: 10
  wandb:
    use: false
    project_name: UAADF
MODEL:
  modelname: resnet18
  pretrained: false
  out_dim: 128
AL:
  n_start: 10000
  n_query: 100
  n_end: 5000
  n_subset: null
  init:
    method: random_select