DEFAULT:
  seed: 0
  savedir: ./results
  exp_name: 'coreset_ratio'

DATASET:
  datadir: ../Data
  batch_size: 32
  test_batch_size: 128
  num_workers: 8
  dataset_name: MVTecAD  # [AnomalyDataset,MVTecAD]
  aug_info: 
    - RandomResizedCrop
  anomaly_ratio: 0
  class_name: bottle  
  img_size: 224
  params:
    normal_ratio: 1

OPTIMIZER:
  opt_name: SGD
  lr: 0

TRAIN:
  epochs: 1
  grad_accum_steps: 1
  mixed_precision: 'no'
  log_interval: 5
  wandb:
    use: false
    project_name: UAADF

MODEL:
  method: PatchCore
  model_name: wide_resnet50_2
  params:
    input_size: 
      - 224 
      - 224
    layers: ['layer2', 'layer3']
    num_neighbors: 9
    coreset_sampling_ratio: 0.1

REFINEMENT:
  nb_round: 0