DEFAULT:
  seed: 0
  savedir: ./results
  exp_name: 'noisedad_nn5'

DATASET:
  datadir: ../Data
  batch_size: 32
  test_batch_size: 32
  num_workers: 8
  dataset_name: MVTecLoco  # [AnomalyDataset,MVTecAD]
  aug_info: 
    - Resize
  class_name: juice_bottle
  img_size: 224
  params:
    anomaly_ratio: 0.2
    baseline: false

OPTIMIZER:
  opt_name: Adam
  lr: 0.005
  params:
    betas: 
    - 0.5
    - 0.999

TRAIN:
  epochs: 1
  grad_accum_steps: 1
  mixed_precision: 'no'
  log_interval: 10
  wandb:
    use: false
    project_name: UARDF
    
SCHEDULER: 
  name: null
  params: null
    

MODEL:
  method: PatchCore
  backbone: wide_resnet50_2
  params:
    input_shape:
      - 3 
      - 224
      - 224
    layers_to_extract_from: 
      - layer2
      - layer3
    faiss_on_gpu: True
    faiss_num_workers: 4
    weight_method: identity 
    threshold: 1
    lof_k: 6
    with_soft_weight: False
    sampler_name: approx_greedy_coreset
    sampling_ratio: 0.1
    anomaly_score_num_nn: 5

REFINEMENT:
  nb_round: 1
  n_query: 0
